### ISSUE TITLE
HiDPI variants do not show up in Settings Manager

### ISSUE THREAD

**Issue by thomholwerda** [donfaustinocortizone/Nashville96#1]
Hi,

Sadly, the HiDPI variants of the themes do not show up in the Xfce Settings Manager for Xfwm4. I've tried both a local and system-wide installation. I'm running Xfce 4.18 on FreeBSD 13.1. I saw that about a month ago a similar issue was fixed, so I'm wondering if this is the same issue re-introduced by Xfce 4.18?

Let me know if you need any more information - this theme is amazing and I really want to use it!

**Comment by donfaustinocortizone** [comment]
Hello.

I'm working on it, i made a new variant with the HDPI folder that was inside the default theme, so you should see now the HDPI variants in the new patch that i'll release until i fix the top left border not showing properly as you can see. 
**Note:** Using a VM because i'm not on my main Linux session currently. 
![screenshot](https://user-images.githubusercontent.com/116418730/209739205-c65e6f3b-858e-4b7d-9ecb-f2338faa40c2.png)

**Comment by thomholwerda** [comment]
Thanks for the quick response! I'll keep an eye on the repo and once you've pushed the fix, I'll clone, test, and report back. Thank you so much!

**Comment by donfaustinocortizone** [comment]
Ok, so i recently updated the repo to include the new HiDPI variants for XFWM4. They should appear now in the Settings Manager.
If you find any issue let me know.

**Comment by thomholwerda** [comment]
Just cloned and installed - and it works! Thanks!
